language: objective-c
osx_image: xcode7.3
xcode_project: Cuckoo.xcodeproj
xcode_scheme: Cuckoo
xcode_sdk: macosx

before_script:
    - gem install cucumber --no-rdoc --no-ri
    - gem install aruba --no-rdoc --no-ri

script:
    - cd Generator
    - bash run_tests.sh
    - cd ..
    - cat Generator/Tests/SourceFiles/Expected/GeneratedMocks.swift
    - cat Generator/Build/tmp/Actual.swift

after_script:
    - sleep 5
